import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <title>Viewership Dashboard</title>
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className='bg-gray-800 shadow p-4 flex space-x-6  mx-auto'>
          <Link href='/' className='text-blue-400 hover:underline'>
            Home
          </Link>
          <Link href='/analytics' className='text-blue-400 hover:underline'>
            Analytics
          </Link>
        </nav>

        {children}
      </body>
    </html>
  )
}
